"""Schemas subpackage - Pydantic v2 artifact and registry models.

Defines ``ArtifactModel`` / ``InternalModel`` base classes, primitives, enums,
provenance, AttackSpec / LabManifest envelopes, and registry meta-schemas.
Architectural source: ``docs/schema.md`` and ``docs/schema-details.md``.
Phase 0 ships the base layer and AttackSpec envelope (Tasks 1-3).

Cross-subpackage imports go through this re-export surface; intra-package
modules import from each sibling module directly.
"""

from cyberlab_gen.schemas.attack_spec import (
    AdvisoryReference,
    AlternativePath,
    AttackSpec,
    ChainBlock,
    ChainStep,
    ChainStepTechniques,
    CveReference,
    DefenderTechniqueBlock,
    DefenseBlock,
    DetectionBlock,
    ExternalRefsBlock,
    ExtractionMetadataBlock,
    ExtrasEntry,
    GapEntry,
    MaterialDiscrepancy,
    MitreTechniqueReference,
    PerStepReproducibility,
    PublisherBlock,
    RealWorldIncident,
    RealWorldIncidentsBlock,
    RelatedBlogReference,
    ReproducibilityBlock,
    SourceBlock,
    ThesisBlock,
    TradecraftNote,
)
from cyberlab_gen.schemas.attack_spec import (
    DetectionFormatEntry as AttackSpecDetectionFormatEntry,
)
from cyberlab_gen.schemas.base import ArtifactModel, InternalModel
from cyberlab_gen.schemas.catalogs import (
    DetectionComponentEntry,
    DetectionComponentsCatalog,
    DetectionFormatEntry,
    DetectionFormatsCatalog,
    ProvisioningMechanismEntry,
    ProvisioningMechanismsCatalog,
    SeverityLevelEntry,
    SeverityLevelsCatalog,
    ThesisTypeEntry,
    ThesisTypesCatalog,
)
from cyberlab_gen.schemas.enums import (
    CitationKind,
    ConfidenceSource,
    DefenderTechniqueKind,
    DefenseApplicability,
    DetectionComponent,
    DetectionFormat,
    ExtractionOutcome,
    IdentifierKind,
    IncidentStatus,
    InputSource,
    LabRole,
    OnDependencyFailure,
    PrereqKind,
    PrereqTiming,
    ProvenanceSource,
    ProvisioningMechanism,
    PublisherKind,
    ReproducibilityLabLevel,
    ReproducibilityTier,
    Severity,
    SpecKind,
    StepComposition,
)
from cyberlab_gen.schemas.ingestion import IngestionResult
from cyberlab_gen.schemas.primitives import (
    ExternalDataSourceId,
    FacetName,
    HttpUrl,
    KebabId,
    NonEmptyString,
    RegistryKey,
    SemVer,
    Sha256Hex,
    SnakeName,
    ThesisType,
    TradecraftName,
)
from cyberlab_gen.schemas.provenance import (
    CitationBlock,
    Provenance,
    ProvenanceBool,
    ProvenanceFloat,
    ProvenanceInt,
    ProvenanceString,
    ProvenanceStringList,
)
from cyberlab_gen.schemas.registries import (
    BundledRegistryFile,
    CacheConfig,
    DiscrepancyMaterialityRule,
    EnrichmentTrigger,
    ExecutionContextEntry,
    ExecutionContextsRegistry,
    ExternalDataSourceEntry,
    ExternalDataSourcesRegistry,
    ExternalSourceEndpoint,
    ExternalSourceParam,
    FacetEntry,
    FacetsRegistry,
    LabCredentialEntry,
    LabCredentialsRegistry,
    OverlayRegistryFile,
    ProposalAuditBlock,
    RateLimit,
    StaticCatalogEntry,
    StaticCatalogsRegistry,
    ValueTypeEntry,
    ValueTypesRegistry,
)

__all__ = [
    "AdvisoryReference",
    "AlternativePath",
    "ArtifactModel",
    "AttackSpec",
    "AttackSpecDetectionFormatEntry",
    "BundledRegistryFile",
    "CacheConfig",
    "ChainBlock",
    "ChainStep",
    "ChainStepTechniques",
    "CitationBlock",
    "CitationKind",
    "ConfidenceSource",
    "CveReference",
    "DefenderTechniqueBlock",
    "DefenderTechniqueKind",
    "DefenseApplicability",
    "DefenseBlock",
    "DetectionBlock",
    "DetectionComponent",
    "DetectionComponentEntry",
    "DetectionComponentsCatalog",
    "DetectionFormat",
    "DetectionFormatEntry",
    "DetectionFormatsCatalog",
    "DiscrepancyMaterialityRule",
    "EnrichmentTrigger",
    "ExecutionContextEntry",
    "ExecutionContextsRegistry",
    "ExternalDataSourceEntry",
    "ExternalDataSourceId",
    "ExternalDataSourcesRegistry",
    "ExternalRefsBlock",
    "ExternalSourceEndpoint",
    "ExternalSourceParam",
    "ExtractionMetadataBlock",
    "ExtractionOutcome",
    "ExtrasEntry",
    "FacetEntry",
    "FacetName",
    "FacetsRegistry",
    "GapEntry",
    "HttpUrl",
    "IdentifierKind",
    "IncidentStatus",
    "IngestionResult",
    "InputSource",
    "InternalModel",
    "KebabId",
    "LabCredentialEntry",
    "LabCredentialsRegistry",
    "LabRole",
    "MaterialDiscrepancy",
    "MitreTechniqueReference",
    "NonEmptyString",
    "OnDependencyFailure",
    "OverlayRegistryFile",
    "PerStepReproducibility",
    "PrereqKind",
    "PrereqTiming",
    "ProposalAuditBlock",
    "Provenance",
    "ProvenanceBool",
    "ProvenanceFloat",
    "ProvenanceInt",
    "ProvenanceSource",
    "ProvenanceString",
    "ProvenanceStringList",
    "ProvisioningMechanism",
    "ProvisioningMechanismEntry",
    "ProvisioningMechanismsCatalog",
    "PublisherBlock",
    "PublisherKind",
    "RateLimit",
    "RealWorldIncident",
    "RealWorldIncidentsBlock",
    "RegistryKey",
    "RelatedBlogReference",
    "ReproducibilityBlock",
    "ReproducibilityLabLevel",
    "ReproducibilityTier",
    "SemVer",
    "Severity",
    "SeverityLevelEntry",
    "SeverityLevelsCatalog",
    "Sha256Hex",
    "SnakeName",
    "SourceBlock",
    "SpecKind",
    "StaticCatalogEntry",
    "StaticCatalogsRegistry",
    "StepComposition",
    "ThesisBlock",
    "ThesisType",
    "ThesisTypeEntry",
    "ThesisTypesCatalog",
    "TradecraftName",
    "TradecraftNote",
    "ValueTypeEntry",
    "ValueTypesRegistry",
]
